sudo: required
dist: bionic
language: java
jdk:
  - orackejdk11
python:
  - "3.6"
services: docker
before_install:
  - sudo apt-get update
  - cd bookstore-app/
  - echo "------------->>>>> Start Maven package <<<<<-------------"
  - mvn clean package
  - cd ..
  - echo "------------->>>>> We are in Docker folder <<<<<-------------"
script:
  - echo "------------->>>>> Ok, Start <<<<<-------------"
  - docker-compose build
before-deploy: 
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy: 
  provider: script
  script:
    docker tag bookstore-app:latest alexalvesdesouza/bookstore-app:$TRAVIS_JOB_ID;
    docker push alexalvesdesouza/bookstore-app:$TRAVIS_JOB_ID;
  on:
    branch: master
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 359407705437.dkr.ecr.us-east-1.amazonaws.com
  - docker tag bookstore-app:latest $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - docker push $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - add-apt-repository ppa:eugenesan/ppa
  - apt-get update
  - apt-get install jq -y
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - echo "AWS ECS DEPLOY IS CONFIGURED"
  - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION -t 240
notifications: 
  email: false