language: bash
services: docker
before_install:
  - echo "Basic Path"
script:
  - docker-compose build
before-deploy: 
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy: 
  provider: script
    docker push alvexalvesdesouza/mysql-bookstore-app;
    docker push alvexalvesdesouza/bookstore-app;
  on:
    branch: master
notifications: 
  email: false